version: '3.8'

services:
    api:
      build:
        context: ./backend
        dockerfile: Dockerfile
      ports:
        - 8000:80
      depends_on:
        - db
        
    db:
      build:
        context: ./backend
        dockerfile: mysql.dockerfile
      env_file:
        - ./backend/.env
      environment:
        MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        MYSQL_ROOT_HOST: "%"
        MYSQL_DATABASE: ${DB_DATABASE}
        MYSQL_USER: ${DB_USERNAME}
        MYSQL_ALLOW_EMPTY_PASSWORD: "1"
      ports:
        - 3306:3306

    frontend:
      build:
        context: ./frontend
        dockerfile: Dockerfile
      ports:
        - 3000:3000
